// Mock data for development
export const mockCustomers = [
  {
    id: '1',
    _id: '1',
    customerId: 'CUST001',
    memberId: 'MEM001',
    fullName: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+91-9876543210',
    dateOfBirth: '1990-01-01',
    gender: 'Male',
    occupation: 'Software Engineer',
    addressLine1: '123 Main Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    postalCode: '400001',
    country: 'India',
    accountType: 'Savings',
    initialDeposit: 10000,
    branch: 'Mumbai Central',
    status: 'Active',
    kycStatus: 'Verified',
    accountNumber: 'ACC001',
    joinedDate: '2023-01-01',
    dateOfJoining: '2023-01-01',
    nomineeName: 'John Doe Sr.',
    nomineeRelation: 'Father',
  },
  {
    id: '2',
    _id: '2',
    customerId: 'CUST002',
    memberId: 'MEM002',
    fullName: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+91-9876543211',
    dateOfBirth: '1985-05-15',
    gender: 'Female',
    occupation: 'Teacher',
    addressLine1: '456 Oak Avenue',
    city: 'Delhi',
    state: 'Delhi',
    postalCode: '110001',
    country: 'India',
    accountType: 'Current',
    initialDeposit: 15000,
    branch: 'Delhi Connaught Place',
    status: 'Active',
    kycStatus: 'Verified',
    accountNumber: 'ACC002',
    joinedDate: '2023-02-01',
    dateOfJoining: '2023-02-01',
    nomineeName: 'Jane Smith Sr.',
    nomineeRelation: 'Mother',
  },
  {
    id: '3',
    _id: '3',
    customerId: 'CUST003',
    memberId: 'MEM003',
    fullName: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '+91-9876543212',
    dateOfBirth: '1988-12-10',
    gender: 'Male',
    occupation: 'Business Owner',
    addressLine1: '789 Pine Street',
    city: 'Bangalore',
    state: 'Karnataka',
    postalCode: '560001',
    country: 'India',
    accountType: 'Business',
    initialDeposit: 25000,
    branch: 'Bangalore Koramangala',
    status: 'Active',
    kycStatus: 'Verified',
    accountNumber: 'ACC003',
    joinedDate: '2023-03-01',
    dateOfJoining: '2023-03-01',
    nomineeName: 'Bob Johnson Sr.',
    nomineeRelation: 'Father',
  },
];
